// Generated by CoffeeScript 1.6.3
(function() {
  this.draw_by_grid = function(dataset) {
    var _this = this;
    return dataset.children.forEach(function(d) {
      console.log(d);
      $("#main-container").append("<div class='article pure-u-1-3'>");
      return $(".article").text("aa");
    });
  };

}).call(this);
