// Generated by CoffeeScript 1.6.3
(function() {
  var apiUrl, appId, create_map, search_word, top_article;

  apiUrl = "http://jlp.yahooapis.jp/MAService/V1/parse";

  appId = "dj0zaiZpPVNpT0xsWGc3ajEwVSZkPVlXazlTVm8zWVZsNk5Xa21jR285TUEtLSZzPWNvbnN1bWVyc2VjcmV0Jng9MjI-";

  $(function() {
    var end, now, start, time,
      _this = this;
    now = new Date();
    time = now.getHours() + ":" + now.getMinutes();
    $('body').html(time);
    start = Date.parse("Apr 1, 2013");
    end = Date.parse(new Date());
    return chrome.history.search({
      "text": "",
      "startTime": start,
      "endTime": end,
      "maxResults": 100
    }, function(array) {
      var hashmap;
      hashmap = create_map(array);
      search_word(hashmap);
      return top_article(hashmap);
    });
  });

  create_map = function(array) {
    var e, hashmap, id, _i, _len;
    hashmap = [];
    for (_i = 0, _len = array.length; _i < _len; _i++) {
      e = array[_i];
      id = e.id;
      if (!hashmap[id]) {
        hashmap[id] = {
          time: e.visitCount,
          url: e.url,
          title: e.title
        };
      }
    }
    return hashmap;
  };

  top_article = function(hashmap) {
    var sorted_hash,
      _this = this;
    sorted_hash = _.sortBy(hashmap, function(e) {
      return e.time;
    });
    sorted_hash.reverse();
    return console.log(sorted_hash);
  };

  search_word = function(hashmap) {
    var titles,
      _this = this;
    titles = "";
    hashmap.forEach(function(page) {
      var q;
      if (page.url.indexOf("https://www.google.co.jp/search?") !== -1) {
        q = page.url.match(/\?q=.*?\&/);
        if (q) {
          q = decodeURI(q[0].replace(/\?q=(.*?)\&/, '$1'));
          q = q.split(/[\s,\+]+/);
          q.forEach(function(title) {
            return titles += title + " ";
          });
          return titles += "<br>";
        }
      }
    });
    return $('body').html(titles);
  };

}).call(this);
