// Generated by CoffeeScript 1.6.3
(function() {
  var Hashmap;

  define(["jquery"], function() {
    return new Hashmap();
  });

  Hashmap = (function() {
    var create_hash, sorted_by_times;

    function Hashmap() {
      console.log("test");
    }

    create_hash = function(array) {
      var e, hash, id, _i, _len;
      hash = [];
      for (_i = 0, _len = array.length; _i < _len; _i++) {
        e = array[_i];
        id = e.id;
        if (!hashmap[id]) {
          hashmap[id] = {
            time: e.visitCount,
            url: e.url,
            title: e.title
          };
        }
      }
      return this.hash = hash;
    };

    sorted_by_times = function() {
      var sorted_hash,
        _this = this;
      sorted_hash = _.sortBy(this.hash, function(e) {
        return e.time;
      });
      sorted_hash.reverse();
      return sorted_hash;
    };

    return Hashmap;

  })();

}).call(this);
