// Generated by CoffeeScript 1.6.3
/*
  memo
  どんな情報を知りたい？
  - bkmしてるページはもういつも見てるからいいんじゃないか。
  - 100回以上アクセスしたページとか。(どこがいる？)
*/


(function() {
  var Hashmap;

  $(function() {
    var end, now, start, time,
      _this = this;
    now = new Date();
    time = now.getHours() + ":" + now.getMinutes();
    start = Date.parse("Apr 1, 2013");
    end = Date.parse(new Date());
    return chrome.history.search({
      "text": "",
      "startTime": start,
      "endTime": end,
      "maxResults": 100
    }, function(array) {
      var hashmap;
      hashmap = new Hashmap(array);
      return console.log(hashmap.sorted_by_times());
    });
  });

  Hashmap = (function() {
    var create_hash;

    function Hashmap(array) {
      this.hash = create_hash(array);
      this.hash_sorted_by_times = null;
    }

    create_hash = function(array) {
      var e, hash, id, _i, _len;
      hash = [];
      for (_i = 0, _len = array.length; _i < _len; _i++) {
        e = array[_i];
        id = e.id;
        if (!hash[id]) {
          hash[id] = {
            time: e.visitCount,
            url: e.url,
            title: e.title
          };
        }
      }
      return this.hash = hash;
    };

    Hashmap.prototype.sorted_by_times = function() {
      var sorted,
        _this = this;
      if (this.hash_sorted_by_times) {
        return this.hash_sorted_by_times;
      } else {
        sorted = _.sortBy(this.hash, function(e) {
          return e.time;
        });
        this.hash_sorted_by_times = sorted.reverse();
      }
      return this.hash_sorted_by_times;
    };

    return Hashmap;

  })();

}).call(this);
