// Generated by CoffeeScript 1.6.3
/*
  memo
  どんな情報を知りたい？
  - bkmしてるページはもういつも見てるからいいんじゃないか。
  - 100回以上アクセスしたページとか。(どこがいる？)
*/


(function() {
  var CreateData, ExtractPageData, Hashmap, searchWord;

  $(function() {
    var end, jsonData, now, start,
      _this = this;
    now = new Date();
    start = Date.parse(new Date()) - 86400000;
    end = Date.parse(new Date());
    jsonData = "";
    return chrome.history.search({
      "text": "",
      "startTime": start,
      "endTime": end,
      "maxResults": 1000
    }, function(array) {
      var hashmap;
      hashmap = new Hashmap(array);
      searchWord(hashmap.hash);
      jsonData = new CreateData(hashmap.sortedByTimes());
      return getJsonData.request(jsonData.jsonFile);
    });
  });

  Hashmap = (function() {
    var create_hash;

    function Hashmap(hash) {
      this.hash = create_hash(hash);
      this.hashSortedByTimes = "";
    }

    create_hash = function(array) {
      var e, hash, id, _i, _len;
      hash = [];
      for (_i = 0, _len = array.length; _i < _len; _i++) {
        e = array[_i];
        id = e.id;
        if (!hash[id]) {
          hash[id] = {
            time: e.visitCount,
            url: e.url,
            title: e.title
          };
        }
      }
      return hash;
    };

    Hashmap.prototype.sortedByTimes = function() {
      var sorted,
        _this = this;
      sorted = _.sortBy(this.hash, function(e) {
        return e.time;
      });
      this.hashSortedByTimes = sorted;
      return this.hashSortedByTimes;
    };

    Hashmap.prototype.getData = function() {
      var _this = this;
      return $.ajax({
        type: 'POST',
        url: "http://itolabchica.appspot.com/hs/json",
        data: this.hashSortedByTimes,
        dataType: 'json',
        success: function(html) {
          return console.log(html);
        }
      });
    };

    return Hashmap;

  })();

  CreateData = (function() {
    var calcDataSize, calcElementNum, createJson, pageCheck, requestApi, showTest;

    function CreateData(hash) {
      this.jsonFile = createJson(hash);
      return this.jsonFile;
    }

    createJson = function(hash) {
      var count, json, urls,
        _this = this;
      count = 0;
      urls = "";
      json = {
        name: "json",
        children: []
      };
      hash.forEach(function(h) {
        var elementNum, url;
        elementNum = 4;
        if (count < elementNum) {
          if (pageCheck(h)) {
            url = h.url + ",";
            console.log(url);
            urls += url;
            return count++;
          }
        }
      });
      return urls;
    };

    requestApi = function(encoded) {
      var req;
      req = new XMLHttpRequest();
      req.open("GET", "http://itolabchica.appspot.com/hs/pageinfo/" + encoded, true);
      req.onload = showTest(this);
      return req.send(null);
    };

    showTest = function(e) {
      console.log("status" + e.target.status);
      return console.log("response:" + e.target.responseText);
    };

    calcElementNum = function() {
      var height, s, width;
      width = $(window).width();
      height = $(window).height();
      s = width * height;
      if (s < 700000) {
        return 4;
      } else if (s < 1500000) {
        return 6;
      } else {
        return 8;
      }
    };

    calcDataSize = function(val) {
      var size;
      size = val < 100 ? 10 : 50;
      return size;
    };

    pageCheck = function(h) {
      var domainType, pageType, t, target, _i, _len;
      if (!this.domainHash) {
        this.domainHash = [];
      }
      if (h.url.indexOf("https") > -1) {
        return false;
      }
      if (h.title.length < 2) {
        return false;
      }
      pageType = h.url.split("/").pop();
      target = ["png", "jpg", "mp3"];
      for (_i = 0, _len = target.length; _i < _len; _i++) {
        t = target[_i];
        if (pageType.indexOf(t) !== -1) {
          return false;
        }
      }
      domainType = h.url.split("/")[2];
      if (!this.domainHash[domainType]) {
        this.domainHash[domainType] = true;
      } else {
        return false;
      }
      if (domainType === "www.youtube.com") {
        return false;
      }
      if (domainType === "127.0.0.1:5000") {
        return false;
      }
      return true;
    };

    return CreateData;

  })();

  ExtractPageData = (function() {
    var createDom, openURI;

    function ExtractPageData(url) {
      this.requestUrl = url;
      openURI(this.requestUrl);
    }

    openURI = function(url) {
      var encoded;
      return encoded = encodeURIComponent(url);
    };

    createDom = function(html) {};

    return ExtractPageData;

  })();

  searchWord = function(hashmap) {
    var key, tag, titles, _i, _len, _results,
      _this = this;
    titles = [];
    hashmap.forEach(function(page) {
      var q;
      if (page.url.indexOf("https://www.google.co.jp/search?") !== -1) {
        q = page.url.match(/\?q=.*?\&/);
        if (q) {
          q = decodeURI(q[0].replace(/\?q=(.*?)\&/, '$1'));
          q = q.split(/[\s,\+]+/);
          return q.forEach(function(title) {
            if (!titles[title]) {
              return titles[title] = 1;
            } else {
              return titles[title] += 1;
            }
          });
        }
      }
    });
    console.log(titles);
    tag = "";
    console.log("key");
    _results = [];
    for (_i = 0, _len = titles.length; _i < _len; _i++) {
      key = titles[_i];
      _results.push(console.log);
    }
    return _results;
  };

}).call(this);
