// Generated by CoffeeScript 1.6.3
(function() {
  var CreateData, Hashmap;

  $(function() {
    var end, jsonData, now, start,
      _this = this;
    now = new Date();
    start = Date.parse(new Date()) - 86400000;
    end = Date.parse(new Date());
    jsonData = "";
    return chrome.history.search({
      "text": "",
      "startTime": start,
      "endTime": end,
      "maxResults": 1000
    }, function(array) {
      var hashmap;
      hashmap = new Hashmap(array);
      searchWordList(hashmap.hash);
      jsonData = new CreateData(hashmap.sortedByTimes());
      return getJsonData.request(jsonData.urlList);
    });
  });

  Hashmap = (function() {
    var create_hash;

    function Hashmap(hash) {
      this.hash = create_hash(hash);
      this.hashSortedByTimes = "";
    }

    create_hash = function(array) {
      var e, hash, id, _i, _len;
      hash = [];
      for (_i = 0, _len = array.length; _i < _len; _i++) {
        e = array[_i];
        id = e.id;
        if (!hash[id]) {
          hash[id] = {
            time: e.visitCount,
            url: e.url,
            title: e.title
          };
        }
      }
      return hash;
    };

    Hashmap.prototype.sortedByTimes = function() {
      var sorted,
        _this = this;
      sorted = _.sortBy(this.hash, function(e) {
        return e.time;
      });
      this.hashSortedByTimes = sorted;
      return this.hashSortedByTimes;
    };

    return Hashmap;

  })();

  CreateData = (function() {
    var calcElementNum, canSelectPage, createJson;

    function CreateData(hash) {
      this.urlList = createJson(hash);
      return this.urlList;
    }

    createJson = function(hash) {
      var count, json, urls,
        _this = this;
      count = 0;
      urls = "";
      json = {
        name: "json",
        children: []
      };
      hash.forEach(function(h) {
        var elementNum, url;
        elementNum = calcElementNum();
        if (count < elementNum) {
          if (canSelectPage(h)) {
            url = h.url + ",";
            urls += url;
            return count++;
          }
        }
      });
      return urls;
    };

    calcElementNum = function() {
      var height, s, width;
      width = $(window).width();
      height = $(window).height();
      s = width * height;
      if (s < 700000) {
        return 6;
      } else if (s < 1500000) {
        return 8;
      } else {
        return 12;
      }
    };

    canSelectPage = function(h) {
      var domainType, pageType, t, target, _i, _len;
      if (!this.domainHash) {
        this.domainHash = [];
      }
      if (h.url.indexOf("https") > -1) {
        return false;
      }
      if (h.title.length < 2) {
        return false;
      }
      pageType = h.url.split("/").pop();
      target = ["png", "jpg", "mp3"];
      for (_i = 0, _len = target.length; _i < _len; _i++) {
        t = target[_i];
        if (pageType.indexOf(t) !== -1) {
          return false;
        }
      }
      domainType = h.url.split("/")[2];
      if (!this.domainHash[domainType]) {
        this.domainHash[domainType] = true;
      } else {
        return false;
      }
      if (domainType === "www.youtube.com") {
        return false;
      }
      if (domainType === "127.0.0.1:5000") {
        return false;
      }
      if (domainType === "localhost:8080") {
        return false;
      }
      return true;
    };

    return CreateData;

  })();

}).call(this);
