// Generated by CoffeeScript 1.6.3
(function() {
  var a, merge, merge_sort, _i, _results;

  merge = function(list1, list2) {
    var i, j, list, _results;
    list = [];
    i = 0;
    j = 0;
    while (i !== list.length && j !== list2.length) {
      if (list[i] < list[j]) {
        list.push(list1[i]);
        i++;
      } else {
        list.push(list2[j]);
        j++;
      }
    }
    while (i !== list1.length) {
      list.push(list[i++]);
    }
    _results = [];
    while (j !== list2.length) {
      _results.push(list.push(list[j++]));
    }
    return _results;
  };

  merge_sort = function(list) {
    var i, list1, list2, target_list;
    target_list = list;
    i = 0;
    while (i < target_list.length - 1) {
      list1 = target_list[i];
      list2 = target_list[i + 1];
    }
    return console.log(target_list);
  };

  a = (function() {
    _results = [];
    for (_i = 0; _i <= 100; _i++){ _results.push(_i); }
    return _results;
  }).apply(this);

  merge_sort(shuffle(a));

}).call(this);
