// Generated by CoffeeScript 1.6.3
(function() {
  this.headerHeight = 38;

  this.sidebarWidth = 300;

  $(function() {
    var mainHeight;
    mainHeight = $(window).height() - headerHeight;
    $("#main-container").css("height", mainHeight);
    return $("#sidebar").css("height", mainHeight);
  });

}).call(this);
